#background_tint 0.0
background_opacity	0.95
dynamic_background_opacity no

#Font
font_family		Monocraft
font_size		10.0
bold_font		auto
italic_font		auto
bold_italic_font	auto

#Disable terminal bell
enable_audio_bell	no

#Disable unsafe closing question
confirm_os_window_close	0

#Set refresh rate
sync_to_monitor		yes

# Optional: remove anti-aliasing for more pixel feel
# allow_bold_font yes
# bold_font yes

# Padding for pixel look
window_padding_width 4

# Standard ANSI colors
# black / dark
color0  #1D1F21
# red / cherry
color1  #FF1C1C
# green
color2  #6EEB83
# yellow / gold
color3  #FFD166
# blue / cyan
color4  #06D6A0
# purple
color5  #9B5DE5
# cyan / light blue
color6  #4EA8DE
# white / light gray
color7  #F8F9FA

# Bright ANSI colors
# dark gray
color8  #6C757D
# bright red / cherry
color9  #FF2D55
# bright green
color10 #50FA7B
# bright yellow / gold
color11 #FFE066
# bright blue / cyan
color12 #00B4D8
# bright purple
color13 #C77DFF
# bright cyan / light blue
color14 #90E0EF
# bright white
color15 #FFFFFF

# Foreground and background
# text color
foreground #E0E0E0
# terminal background
background #1D1F21
