#background_tint 0.0
background_opacity	0.95
dynamic_background_opacity no

#Font
font_family		Monocraft
font_size		12.0
bold_font		auto
italic_font		auto
bold_italic_font	auto

#Disable terminal bell
enable_audio_bell	no

#Disable unsafe closing question
confirm_os_window_close	0

#Set refresh rate
sync_to_monitor		yes

# Colors (Celeste palette)
background #1D1F21   # dark blue/gray
foreground #A4D1FF   # light blue
color0  #1D1F21       # black
color1  #FF71CE       # pink/red
color2  #05FFA1       # green
color3  #FFD700       # yellow
color4  #01CDFE       # cyan
color5  #B967FF       # purple
color6  #A4D1FF       # light blue
color7  #ffffff       # white

# Optional: remove anti-aliasing for more pixel feel
# allow_bold_font yes
# bold_font yes

# Padding for pixel look
window_padding_width 4
